/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RuntimeCode {
  expressions: string
  render: string
  hydration: string
  styles: string
  script: string
  stateInit: string
  bundle: string
  npmImports: Array<ScriptImport>
  errors: Array<string>
}
export interface ScriptImport {
  source: string
  specifiers: string
  typeOnly: boolean
  sideEffect: boolean
}
export declare function generateRuntimeCode(inputJson: string): RuntimeCode
export declare function generateCodegenIntent(): string
export declare function resolveComponentsNative(irJson: string, componentsJson: string): string
/** Discover all components in a directory */
export declare function discoverComponentsNative(baseDir: string): any
export declare function extractStylesNative(source: string): Array<string>
export declare function extractPageBindingsNative(script: string): Array<string>
export declare function extractPagePropsNative(script: string): Array<string>
export interface VirtualModule {
  id: string
  code: string
}
export interface BundlePlan {
  entry: string
  platform: string
  format: string
  resolveRoots: Array<string>
  virtualModules: Array<VirtualModule>
}
/**
 * Manifest export for the bundler's capability-based chunking.
 * This is the Compiler → Bundler handshake contract.
 */
export interface ZenManifestExport {
  /** Entry point path */
  entry: string
  /** Pre-rendered HTML template */
  template: string
  /** Whether this page uses reactive state */
  usesState: boolean
  /** Whether this page has event handlers */
  hasEvents: boolean
  /** Whether this page is fully static */
  isStatic: boolean
  /** CSS classes used by this page (for pruning) */
  cssClasses: Array<string>
  /** Required runtime capabilities (as strings for JS interop) */
  requiredCapabilities: Array<string>
  /** Compiled script content (author code) */
  script: string
  /** Compiled expressions */
  expressions: string
  /** Compiled styles */
  styles: string
  /** NPM imports */
  npmImports: string
}
export interface FinalizedOutput {
  html: string
  hasErrors: boolean
  errors: Array<string>
  /** Manifest for bundler's capability-based chunking */
  manifest?: ZenManifestExport
}
export declare function finalizeOutputNative(irJson: any, compiledJson: any): FinalizedOutput
export declare function parseTemplateNative(html: string, filePath: string): any
export declare function parseScriptNative(html: string): any | null
export declare function isComponentTagNative(tagName: string): boolean
/**
 * Full Zenith compilation entry point - the "One True Syscall"
 *
 * Combines: parse_template + parse_script → ZenIR → component resolution →
 * transform → finalize → FinalizedOutput
 */
export interface ParseFullOptions {
  mode?: string
  useCache?: boolean
  components?: any
  layout?: any
  props?: any
}
export declare function parseFullZenNative(source: string, filePath: string, optionsJson: string): any
export interface ExpressionAnalysisResult {
  id: string
  classification: string
  dependencies: Array<string>
  usesState: boolean
  usesLoopContext: boolean
}
export interface EvaluatedExpression {
  id: string
  expressionType: string
  dependencies: Array<string>
  usesState: boolean
  usesLoopContext: boolean
  classificationJson: string
}
export interface AnalysisOutput {
  results: Array<ExpressionAnalysisResult>
  bindingCount: number
}
export declare function lowerFragmentsNative(nodesJson: string, expressionsJson: string, filePath: string): string
export declare function evaluateExpressionNative(id: string, code: string, knownBindingsJson: string, loopContextJson?: string | undefined | null): EvaluatedExpression
export declare function classifyExpressionNative(code: string): string
export declare function analyzeExpressions(inputJson: string): AnalysisOutput
export interface Binding {
  id: string
  type: string
  target: string
  expression: string
  location?: SourceLocation
  loopContext?: LoopContext
}
export interface TransformOutput {
  html: string
  bindings: Array<Binding>
}
export declare function transformTemplateNative(nodesJson: string, expressionsJson: string): TransformOutput
export interface CompilerError {
  code: string
  errorType: string
  message: string
  guarantee: string
  file: string
  line: number
  column: number
  context?: string
  hints: Array<string>
}
export interface SourceLocation {
  line: number
  column: number
}
export interface LoopContext {
  variables: Array<string>
  mapSource?: string
}
export declare function validateIr(irJson: string): CompilerError | null
export declare function compileBridge(): string
export declare class ResolutionContext { }
