/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RuntimeCode {
  expressions: string
  render: string
  hydration: string
  styles: string
  script: string
  stateInit: string
  bundle: string
  npmImports: Array<ScriptImport>
  errors: Array<string>
}
export interface ScriptImport {
  source: string
  specifiers: string
  typeOnly: boolean
  sideEffect: boolean
}
export declare function generateCodegenIntent(): string
/**
 * Manifest export for the bundler's capability-based chunking.
 * This is the Compiler → Bundler handshake contract.
 */
export interface ZenManifestExport {
  /** Entry point path */
  entry: string
  /** Pre-rendered HTML template */
  template: string
  /** Whether this page uses reactive state */
  usesState: boolean
  /** Whether this page has event handlers */
  hasEvents: boolean
  /** Whether this page is fully static */
  isStatic: boolean
  /** CSS classes used by this page (for pruning) */
  cssClasses: Array<string>
  /** Required runtime capabilities (as strings for JS interop) */
  requiredCapabilities: Array<string>
  /** Compiled script content (author code) */
  script: string
  /** Full hydrated bundle */
  bundle: string
  /** Compiled expressions */
  expressions: string
  /** Compiled styles */
  styles: string
  /** NPM imports */
  npmImports: string
}
export interface FinalizedOutput {
  html: string
  hasErrors: boolean
  errors: Array<string>
  /** Manifest for bundler's capability-based chunking */
  manifest?: ZenManifestExport
}
/**
 * Full Zenith compilation entry point - the "One True Syscall"
 *
 * Combines: parse_template + parse_script → ZenIR → component resolution →
 * transform → finalize → FinalizedOutput
 */
export interface ParseFullOptions {
  mode?: string
  useCache?: boolean
  components?: any
  layout?: any
  props?: any
}
export declare function parseFullZenNative(source: string, filePath: string, optionsJson: string): any
export interface Binding {
  id: string
  type: string
  target: string
  expression: string
  location?: SourceLocation
  loopContext?: LoopContext
}
export interface TransformOutput {
  html: string
  bindings: Array<Binding>
}
export declare function transformTemplateNative(nodesJson: string, expressionsJson: string): TransformOutput
export interface CompilerError {
  code: string
  errorType: string
  message: string
  guarantee: string
  file: string
  line: number
  column: number
  context?: string
  hints: Array<string>
}
export interface SourceLocation {
  line: number
  column: number
}
export interface LoopContext {
  variables: Array<string>
  mapSource?: string
}
export declare function compileBridge(): string
export declare class ResolutionContext { }
